### ISSUE TITLE
从小程序端，无法正常返回android 应用，点击小程序按钮无反应

### ISSUE THREAD

**Issue by ai2101039** [react-native-hero/wechat#3]

**Comment by ai2101039** [comment]
刚才排查了下，实际上是点击后，app崩溃了，提示，com.XXXXXX.wechat.NotifyActivity}: java.lang.ClassNotFoundException: Didn't find class 
实际上这个class 是存在的

**Comment by ai2101039** [comment]
我解决了这个问题，报错的 notFound NotifyActivity 实际上 是 notFound WXEntryActivity  或者 WXPayEntryActivity

作者在readme中的描述，有瑕疵

> 在 manifest 文件的 application 节点下新增一个 activity 和两个 activity-alias，里面加上 exported 和 launchMode 属性，其中 exported 设置为 true， launchMode 设置为 singleTask：

**正确的应该是，我们新增三个 activity 和两个 activity-alias**

操作如下
在包名目录下，创建一个wxapi目录，里面创建 WXEntryActivity 和 WXPayEntryActivity，继承 Activity，onCreat 内，执行 finish动作。

**Comment by musicode** [comment]
赞，有问题再反馈，我比较忙，这个月没空管开源项目
